---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role is to remove the subcloud backup data of the specified
#   software release from local/central storage.
#
- name: Validate user input
  import_tasks: validate_input.yml

- name: Prepare remote execution environment
  include_role:
    name: common/prepare-env
  when: local

- name: Remove {{ software_version }} backup data for {{ inventory_hostname }}
  file:
    path: "{{ removal_dir }}"
    state: absent
  connection: "{{ target_connection }}"
