---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This will complete the restoration process.
#   Applying any missing changes or creating any missing flags
#   that are not created during optimized restore.

- set_fact:
    _remove_items:
      - "{{ ansible_remote_tmp|default('') }}"
      - "{{ override_files_dir }}/{{ override_filename }}"
      - "{{ target_backup_dir }}/{{ override_filename }}"

- set_fact:
    _restore_remove_items:
      - "{{ platform_backup_fqpn }}"
      - "{{ registry_backup_fqpn|default('') }}"
  when: initial_backup_dir != target_backup_dir

- set_fact:
    _upgrade_remove_items:
      - "{{ temp_upgrade_platform_dir }}"
      - "{{ mini_restore_data_file }}"
      - "{{ patching_restore_data_file }}"
  when: upgrade_in_progress

- name: Remove temporary files and directories used during restore
  file:
    path: "{{ item }}"
    state: absent
  loop: >
    {{
      _remove_items + _restore_remove_items|default([]) + _upgrade_remove_items|default([])
      | reject('equalto', '')
    }}

- name: Combine required flags
  set_fact:
    all_required_flags: "{{ default_required_flags + extra_required_flags }}"

- name: Set restore in progress for sysinv
  shell: "source /etc/platform/openrc; system restore-start"

# Optimized restore does not create all the required flags.
# Any missing flags will be created here.
- name: Set flags for puppet
  file:
    path: "{{ (flags_dir, item) | path_join }}"
    state: touch
  loop: "{{ all_required_flags }}"

# If the system is online, restore was most likely successful.
# Network instability on management network can
# cause system to not be online immediately.
- name: Check if system is in online state
  shell: source /etc/platform/openrc; system host-show controller-0 --column availability --format value
  register: check_online
  retries: "{{ system_online_retries }}"
  delay: "{{ system_online_retry_delay }}"
  until: check_online.stdout == "online"
