---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Precheck to ensure all subcloud backup and restore related playbooks are
# executed on the system controller and the overrides file is provided.
#
- name: Fail if subcloud_bnr_overrides parameter is not specified
  fail:
    msg: "Location of operation overrides must be specified."
  when: subcloud_bnr_overrides is undefined

- name: Load input parameters for operation
  include_vars: "{{ subcloud_bnr_overrides }}"

- name: Retrieve the distributed cloud role
  shell: source /etc/platform/platform.conf; echo $distributed_cloud_role
  register: dc_role
  connection: local

- name: Fail if the playbook is not run on the system controller
  fail:
    msg: >
      This playbook is intended to be executed on the system controller
      of a distributed cloud system.
  when: dc_role.stdout != 'systemcontroller'
