---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   Restore docker image data if supplied in backup.

- name: Stop docker services
  systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ docker_services }}"

- name: Restore image registry data to /var/lib/docker-distribution
  command: >
    tar --use-compress-program=pigz
        -xpf {{ registry_backup_fqpn }}
        -C / --overwrite var/lib/docker-distribution
  args:
    warn: false
  when: restore_registry_filesystem

# The following task is executed when the backup does not contain image registry filesystem archive
# but the prestage directory (/opt/platform-backup/<sw-version>) does.
- name: Restore prestaged image registry data to /var/lib/docker-distribution if exists
  command: >
    tar --use-compress-program=pigz
        -xpf {{ prestage_registry_filesystem.stat.path }}
        -C / --overwrite var/lib/docker-distribution
  args:
    warn: false
  when:
    - not restore_registry_filesystem
    - prestage_registry_filesystem is defined
    - prestage_registry_filesystem.stat.exists

- name: Disable local registry authentication
  command: "sed -i '/auth:/,$d' /etc/docker-distribution/registry/config.yml"
  args:
    warn: false

- name: Restart docker services
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ docker_services }}"

# Docker images archive source validation
- import_role:
    name: common/validate-image-archives
