---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   Restore kubernetes service.
#   During restoration of kubernetes, images will be pushed to local
#   registry.  If the images were not included in the backup
#   they will be downloaded in the same way as during a bootstrap.

# Cluster host floating IP is required on subclouds for etcd restoration
- name: Get cluster host floating IP
  shell: |-
    source /etc/platform/openrc
    system addrpool-list | grep cluster-host-subnet | cut -d'|' -f8
  failed_when: not cluster_vip.stdout
  register: cluster_vip

- name: Configure controller host addresses
  command: "ip addr add {{ cluster_vip.stdout_lines[0] }} dev lo scope host"

# We may need to update /etc/hosts because registry.central will not be
# available on system controllers or subclouds because dnsmasq is not brought up.
- name: Check if registry.central is present in sysinv
  shell: |-
    source /etc/platform/openrc
    system addrpool-list | grep system-controller-oam-subnet | cut -d'|' -f8
  register: sc_oam_vip

- name: Add host route to registry.central if present
  lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "{{ sc_oam_vip.stdout_lines[0].strip() }} registry.central"
  when: sc_oam_vip.stdout

- name: Check if archived kubelet dir present
  shell: "tar -tf {{ platform_backup_fqpn }} | grep 'var/lib/kubelet'"
  args:
    warn: false
  register: kubelet_dir_result

- name: Restore kubelet configuration
  command: "tar -C / -xpf {{ platform_backup_fqpn }} --overwrite var/lib/kubelet/"
  args:
    warn: false
  when: kubelet_dir_result.rc == 0

- name: Get Kubernetes version
  import_role:
    name: common/get-kube-version

- name: Mount k8s bind mount
  import_role:
    name: common/k8s-bind-mount

- name: Add containerd-pod-recovery service
  template:
    src: roles/optimized-restore/templates/containerd-pod-recovery.service.j2
    dest: /etc/systemd/system/containerd-pod-recovery.service
    mode: 0644
    owner: root
    group: root

- name: Enable containerd-pod-recovery service
  systemd:
    name: containerd-pod-recovery.service
    daemon_reload: true
    enabled: true

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable kubelet
  systemd:
    name: kubelet
    state: stopped
    enabled: true

- name: Start containerd service
  systemd:
    name: containerd
    state: restarted

# Running push-docker-images and bringup-kubemaster increases playbook time,
# but it decreases unlock time by around the same amount.
- name: Populate local image registry
  import_role:
    name: common/push-docker-images

- name: Bring up Kubernetes master
  import_role:
    name: common/bringup-kubemaster
