---
#
# Copyright (c) 2021 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
- name: Stat sysctl file configuration
  stat:
    path: /etc/sysctl.d/99-sysctl.conf

- name: Enable net.ipv4.ip_forward in sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    state: present

- name: Add net.ipv4.conf.tunl0.rp_filter in sysctl for calico
  lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.conf.tunl0.rp_filter=0
    state: present
  failed_when: false
