---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Validate if initial_backup_dir is supplied
  fail:
    msg: "initial_backup_dir variable not provided"
  when: not initial_backup_dir

- name: Validate initial_backup_dir exists
  stat:
    path: "{{ initial_backup_dir }}"
  register: initial_backup_dir_exists

- name: Fail if initial_backup_dir does not exists
  fail:
    msg: "Directory initial_backup_dir: {{ initial_backup_dir }} does not exist"
  when: not initial_backup_dir_exists.stat.exists

- name: Set vault backup directory fact
  set_fact:
    vault_backup_dir: "{{ initial_backup_dir }}/hc_vault"

- name: Create vault subdirectory in initial_backup_dir
  file:
    path: "{{ vault_backup_dir }}"
    state: directory
    mode: 0755

- name: Check if encrypt is enabled
  set_fact:
    vault_encrypt: true
  when: encrypt_hc_vault_secret | length > 0

- name: Check vault apply for backup
  block:
  - name: Check if vault is applied
    shell: |
      source /etc/platform/openrc
      system application-show vault --format value --column status
    register: vault_applied_exists

  - name: Fail if vault is not applied
    fail:
      msg: "Vault application is not applied"
    when: vault_applied_exists.stdout != "applied"
  when: vault_mode == "backup"

- name: Validate vault health for restore.
  block:
  - name: Set backup file path
    set_fact:
      backup_filepath: "{{ initial_backup_dir }}/{{ backup_filename }}"

  - name: Find backup tarball
    shell: |
      ls {{ backup_filepath }}
    register: backup_tarball

  - name: Fail if vault backup tarball not found
    fail:
      msg: "Vault snapshot tarball: {{ backup_filename }} was not found"
    when: backup_tarball.stdout | length == 0

  - name: Validate if vault application is ready to be restored
    script: validate_recover_vault.sh
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    register: validate_vault_result
    failed_when: validate_vault_result.rc != 0

  rescue:
    - name: Display vault validation script output if exists
      debug:
        msg: "{{ validate_vault_result.stdout }}"
      when: validate_vault_result is defined
  when: vault_mode == "restore"

- name: Find vault manager pod
  shell: >-
    kubectl get pods -n vault | grep "vault-manager" | cut -d " " -f 1
  register: vault_manager_pod_name
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Fail if vault manager pod is not found
  fail:
    msg: "Vault manager pod is not found"
  when: vault_manager_pod_name.stdout | length == 0
