---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role is used to copy prestaging repo from the system controller
#   (prestage for upgrade) or local ostree repo (prestage for reinstall)
#   to the subcloud prestage directory.

- name: Set local prestaging repo path on the subcloud
  set_fact:
    local_prestaging_repo: "{{ prestage_dir }}/prestaging_repo"

- name: Ensure local prestaging repo path exist
  file:
    path: "{{ local_prestaging_repo }}"
    state: directory
    owner: root
    mode: 0755
    recurse: yes

- block:
  - name: Copy prestaging repo from local ostree repo
    include_role:
      name: prestage/prepare-ostree-repo
    vars:
      release_id: "{{ host_software_version }}"
      repo_path: "{{ local_prestaging_repo }}"

  when: prestage_reason == 'reinstall'

- block:
  - name: Temporarily change the ownership of the prestage dir on the subcloud
    file:
      path: "{{ platform_backup_dir }}"
      state: directory
      owner: sysadmin
      recurse: yes

  - name: Copy prestaging repo from system controller to {{ inventory_hostname }}
    command: >
      sshpass -p {{ ansible_ssh_pass }}
      rsync -ap --delete -e 'ssh -o StrictHostKeyChecking=no' {{ prestaging_repo }}
      {{ ansible_ssh_user }}@{{ inventory_hostname }}:{{ prestage_dir }}
    register: prestage_transfer
    retries: 3
    delay: 5
    until: prestage_transfer.rc == 0
    no_log: true
    connection: local

  - name: Restore the ownership of the prestage dir on the subcloud
    file:
      path: "{{ platform_backup_dir }}"
      state: directory
      owner: root
      recurse: yes

  when: prestage_reason == 'upgrade'

- name: Mark software prestaging as completed
  file:
    path: "{{ prestage_dir }}/{{ packages_prestage_completed_flag }}"
    state: touch
    owner: root
    mode: 0644
