---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   These tasks do the preparation for kubernetes staged versions.
#

- block:
  - name: Set Kubernetes local directory
    set_fact:
      kube_local_dir: "/usr/local/kubernetes"
      kube_symlink_dir: "/var/lib/kubernetes"

  # When updating kubernetes, kubeadm, and kubelet need to be updated separately
  # so we will have "stage1" and "stage2" symlinks under
  # /var/lib/kubernetes to separate these different stages.
  - name: Link Kubernetes stage1 and stage2 directories
    ansible.builtin.file:
      src: "{{ kube_local_dir }}/{{ kubernetes_version }}/{{ item }}"
      dest: "{{ kube_symlink_dir }}/{{ item }}"
      state: link
    with_items:
      - "stage1"
      - "stage2"

  when: kubernetes_version is defined
