---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# TASKS DESCRIPTION:
#   Prepare and transfer backup overrides to the subcloud for the execution
#   of local backup playbook.
#
- block:
  - name: Create a vault id file
    copy:
      dest: "{{ vault_id_file }}"
      content: |
        "{{ vault_pass }}"
      mode: '0600'
      remote_src: no
    register: local_vault_id
    connection: local

  - name: Encrypt backup overrides file
    command: ansible-vault encrypt {{ backup_overrides }} --vault-id {{ vault_id_file }}
    register: local_encrypt_result
    connection: local

  - name: Copy vault id file to the subcloud
    copy:
      src: "{{ vault_id_file }}"
      dest: "{{ vault_id_file }}"
      mode: '0400'

  - name: Copy encrypted backup override file to the subcloud
    copy:
      src: "{{ backup_overrides }}"
      dest: "{{ backup_overrides }}"
      owner: root
      group: root
      decrypt: no
      backup: no

  - name: Decrypt backup override file
    command: ansible-vault decrypt {{ backup_overrides }} --vault-id {{ vault_id_file }}

  always:
    - name: Remove local backup overrides file
      file:
        path: "{{ backup_overrides }}"
        state: absent
      connection: local

    - name: Remove vault id file from the system controller
      file:
        path: "{{ vault_id_file }}"
        state: absent
      connection: local

    - name: Remove vault id file from the subcloud
      file:
        path: "{{ vault_id_file }}"
        state: absent
