---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# TASKS DESCRIPTION:
#   Transfer subcloud backup to the system controller. Restore the previous
#   backup if exists in case of transfer failure.
#
- name: Transfer subcloud platform backup file to the system controller
  block:
  - name: Create backup storage directory for {{ inventory_hostname }} on system controller
    file:
      path: "{{ central_backup_dir }}"
      state: directory
      mode: '0700'
      owner: root
      group: root
      recurse: yes
    connection: local

  - name: Get files in {{ backup_dir }} on {{ inventory_host_name }}
    find:
      paths: "{{ backup_dir }}"
      patterns: "{{ platform_backup_filename_prefix }}*"
    register: backup_files

  - name: Get latest backup file
    set_fact:
      local_backup_file: "{{ (backup_files.files | sort(attribute='mtime') | last).path }}"

  # This task only works without privilege escalation. Setting become to true
  # makes the rsync on the remote host to be run with sudo, and since it's not
  # possible to provide a password (limitation from rsync itself), the file transfer fails.
  # Since the whole restore playbook is being run by root, the central_backup_dir
  # can be accessed to save the file without setting become to true.
  - name: Transfer platform backup of {{ inventory_hostname }} to the system controller
    synchronize:
      mode: pull
      src: "{{ local_backup_file }}"
      dest: "{{ central_backup_dir }}"
    register: backup_transfer
    until: backup_transfer.rc == 0
    retries: 3
    delay: 2
    become: false

  - name: Remove previous backup upon successful subcloud backup (central storage)
    file:
      path: "{{ previous_backup_dir }}"
      state: absent
    connection: local
    when: previous_backup_dir is defined

  rescue:
    - name: Remove empty/incomplete backup directory on the system controller
      file:
        path: "{{ central_backup_dir }}"
        state: absent
      connection: local

    - name: Restore previous backup upon failure
      command: mv {{ previous_backup_dir }} {{ central_backup_dir }}
      connection: local
      when: previous_backup_dir is defined

    - name: Force fail post rescue of transfer task failure
      fail:
        msg: "An error occurred while transferring backup file to the system controller."

  always:
    - name: Remove staging backup file/directory from {{ inventory_hostname }}
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ local_backup_file }}"
        - "{{ default_local_staging_dir }}"
