---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASK DESCRIPTION:
#   This will wipe any Ceph OSDs during a bootstrap or optionally
#   wipe them during restore.
#

# TODO(jkraitbe): Consider moving this check to happen earlier
# Wipe ceph osds
# Note that due to Ansible mishandling of boolean values via extra-vars we are
# adding supplementary validation here.
# See: https://github.com/ansible/ansible/issues/17193
- name: Check for Ceph data wipe flag
  fail:
    msg: "wipe_ceph_osds is misconfigured. Valid value is either 'true' or 'false'"
  when: (mode == "restore") and (not wipe_ceph_osds | type_debug == 'bool') and
        (wipe_ceph_osds != 'true') and
        (wipe_ceph_osds != 'false')

- block:
    - name: Wipe ceph osds
      script: wipe_osds.sh
      register: results

    - name: Result of wiping ceph osds
      debug: var=results.stdout_lines

  when: (mode == "bootstrap") or
        (mode == "restore" and wipe_ceph_osds|bool)
