---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook invokes role bootstrap/install-platform-certificates
# to create the openldap certificate during the upgrade to 22.12.
# It will be automatically executed by an upgrade script during
# the upgrade process.
#

- hosts: all
  become: yes

  vars:
    kubeadm_pki_dir: /etc/kubernetes/pki

  roles:
    - bootstrap/install-platform-certificates
