---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook copies prestage packages (Centos) or ostree repo (Debian)
# from the release feed (Centos: /www/pages/feed/rel-<release>,
# Debian: /var/www/pages/feed/rel-<release>) to the prestage directory
# (/opt/platform-backup/<release>).
# The playbook is meant to be integrated with the dcmanager to provide
# subcloud prestaging functionality.
#
# Usage:
#   ansible-playbook prestage_sw_packages.yml -i <inventory-file> \
#      -e "software_version=<release-number>"

- hosts: all
  gather_facts: no

  vars_files:
    - vars/prestage/main.yml

  vars:
    prestage_type: "packages"
    platform_backup_dir: /opt/platform-backup

  roles:
    - role: prestage/prepare-env

    - role: prestage/prestage-sw-packages
      when: prestage_os_type == 'debian'
      become: yes

    - role: prestage/prestage-sw-packages-centos
      when: prestage_os_type == 'centos'
      become: yes

    - role: prestage/prestage-patches
      when: host_patches_exist
      become: yes
