---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook copies prestaging ostree repo from the system controller to
# /opt/platform-backup/<release-number> for subcloud upgrade or reinstall.
# The playbook is meant to be integrated with the dcmanager to provide
# subcloud prestaging functionality.
#
# Usage:
#   ansible-playbook prestage_sw_packages.yml -i <inventory-file> \
#      -e "software_version=<release-number>"

- hosts: all
  gather_facts: no

  vars:
    prestage_type: "packages"
    platform_backup_dir: /opt/platform-backup
    prestaging_repo: /var/run/prestaging_repo

  roles:
    - prestage/prepare-env
    - { role: prestage/prestage-sw-packages, become: yes }
