---
#
# Copyright (c) 2021-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- hosts: all
  gather_facts: no

  vars_files:
    - vars/common/main.yml
    - host_vars/rehome-subcloud/default.yml

  roles:
    - common/prepare-env
    - common/validate-target
    - rehome-subcloud/validate-before-rehome
    - common/check-services-status
    - rehome-subcloud/prepare-env
    - rehome-subcloud/update-ca-cert
    - common/update-sc-admin-endpoints
    - common/update-sc-cert
    - rehome-subcloud/update-network-config
    - { role: rehome-subcloud/update-keystone-data, become: yes }
    - common/check-services-status
