---
#
# Copyright (c) 2021-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- hosts: all
  gather_facts: no

  vars_files:
    - vars/common/main.yml
    - host_vars/rehome-subcloud/default.yml

  roles:
    - common/prepare-env
    - common/validate-target
    - { role: rehome-subcloud/validate-before-rehome, become: yes }
    - { role: common/check-services-status, become: yes }
    - { role: rehome-subcloud/prepare-env, become: yes }
    - { role: rehome-subcloud/update-ca-cert, become: yes }
    - { role: rehome-subcloud/update-network-config, become: yes }
    - { role: common/update-sc-cert, become: yes }
    - { role: rehome-subcloud/update-keystone-data, become: yes }
    - { role: common/check-services-status, become: yes }
