---
#
# Copyright (c) 2019-2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- hosts: all
  gather_facts: no

- name: "Running restore playbook {{ restore_playbook }}"
  import_playbook: "{{ restore_playbook }}"
  vars:
    restore_mode: "old"
    restore_playbook: "{{ 'restore_optimized.yml' if restore_mode == 'optimized' else 'restore_platform_old.yml' }}"
