---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# requires one variable passed:
# initial_backup_dir = The resulting backup package will be found here.

- hosts: all
  gather_facts: no

  vars_files:
    - host_vars/backup-restore/default.yml

  vars:
    password_change: false
    vault_encrypt: false
    # override encrypt_hc_vault_secret when calling the playbook to enable extra encryption
    encrypt_hc_vault_secret: ""
    vault_mode: "backup"
    op_mode: "standalone"

  roles:
    - role: common/prepare-env
    - role: vault/prepare_env
      become: yes
    - role: vault/vault_backup
      become: yes
