---
#
# Copyright (c) 2021 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# The dockerd and containerd will be restarted after the config files
# from the controllers are copied to the edgeworker nodes. Then the
# configuration of the daemon will be updated.
#
- name: Restart containerd
  command: /bin/true
  notify:
    - Containerd | restart containerd
    - Containerd | wait for containerd

- name: Containerd | restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Containerd | wait for containerd
  command: "{{ containerd_bin_dir }}/ctr images ls -q"
  register: containerd_ready
  retries: 8
  delay: 4
  until: containerd_ready.rc == 0

- name: Restart dockerd
  command: /bin/true
  notify:
    - Docker | reload systemd
    - Docker | reload docker
    - Docker | wait for docker

- name: Docker | reload systemd
  systemd:
    daemon_reload: true

- name: Docker | reload docker
  service:
    name: docker
    state: restarted

- name: Docker | wait for docker
  command: "{{ docker_bin_dir }}/docker images"
  register: docker_ready
  retries: 20
  delay: 1
  until: docker_ready.rc == 0

# This will be called after kubeadm join to update specific node-ip
# and cri socket config.
- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon-reload: yes
