---
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Handler to reload sshd service

- name: reload sshd
  service:
    name: sshd
    state: reloaded
  become: true
