---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   These tasks validate and update subcloud endpoints
#

- name: "Get {{ service }} admin endpoint UUID"
  shell: >-
    source /etc/platform/openrc; openstack endpoint list |
    awk '($12 == "admin" && $6 == "{{ service }}") { print $2 }'
  register: admin_endpoint_UUID

- name: "Check {{ service }} admin endpoint URL"
  shell: >-
    source /etc/platform/openrc; openstack endpoint list |
    grep "admin" | grep "{{ service }}" | grep "{{ sc_floating_address }}" |
    awk '{print $0}'
  register: Check_admin_endpoint_URL

- name: "Correct {{ service }} admin endpoint"
  shell: >-
    source /etc/platform/openrc; openstack endpoint set
    --region "{{ sc_region_name.stdout }}" --interface admin
    --url https://{{ parsed_sc_floating_address }}:{{ port }}
    --service "{{ service }}" --enable "{{ admin_endpoint_UUID.stdout }}"
  when: Check_admin_endpoint_URL.stdout == ''
