---
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role contains common components (tasks, vars, etc.) that
#   can be shared by all the backup and restore playbooks.

- name: Ensure archive dir exists
  file:
    path: "{{ backup_dir }}"
    state: directory
  become: true

- name: Retrieve software version number
  # lookup module does not work with /etc/build.info as it does not have ini
  # format. Resort to shell source.
  shell: source /etc/build.info; echo $SW_VERSION
  register: sw_version_result

- name: Fail if software version is not defined
  fail:
    msg: "SW_VERSION is missing in /etc/build.info"
  when: sw_version_result.stdout_lines|length == 0

- name: Retrieve system type
  shell: source /etc/platform/platform.conf; echo $system_type
  register: system_type_result

- name: Fail if system type is not defined
  fail:
    msg: "system_type is missing in /etc/platform/platform.conf"
  when: system_type_result.stdout_lines|length == 0

- name: Set software version fact
  set_fact:
    software_version: "{{ sw_version_result.stdout_lines[0] }}"
    system_type: "{{ system_type_result.stdout_lines[0] }}"
