---
#
# Copyright (c) 2020-2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role performs the following tasks:
#     1. Verify that the target is in the right state for images restore.
#     2. Transfer the backup tarball to the target if it is off-box, otherwise
#        copy it to the designated staging directory (/opt/platform-backup).
#     3. Create restore_in_progress flag.

- name: Check if restoring user images is already in progress
  stat:
    path: "{{ restore_user_images_in_progress_flag }}"
  register: restore_user_images_in_progress

- name: Fail if restoring user images is already in progress
  fail:
    msg: "Restoring user images is already in progress!"
  when: restore_user_images_in_progress.stat.exists

- name: Perform generic B&R environment validation
  import_role:
    name: backup-restore/prepare-env

- name: Transfer backup tarball to target if the file is off-box
  include_role:
    name: backup-restore/transfer-file
  when: on_box_data|bool == false

- block:
  - name: Copy the backup tarball to {{ target_backup_dir }} if the file is already on-box
    copy:
      src: "{{ initial_backup_dir }}/{{ backup_filename }}"
      dest: "{{ target_backup_dir }}"
      remote_src: yes
    when: on_box_data|bool == true

  - name: Create {{ restore_user_images_in_progress_flag }} flag file
    file:
      path: "{{ restore_user_images_in_progress_flag }}"
      state: touch
  become: yes
  become_user: root
