---
#
# Copyright (c) 2021 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

containerd_bin_dir: /usr/local/bin
containerd_version: '1.3.0'
containerd_versioned_pkg:
  '1.3.3': containerd-1.3.3-0ubuntu1

docker_bin_dir: /usr/bin
docker_version: '18.09.6'
docker_versioned_pkg:
  '18.09.6': 5:18.09.6~3-0~ubuntu-bionic

k8s_version: '1.18.1'

kubeadm_versioned_pkg:
  '1.16.2': kubeadm=1.16.2-00
  '1.18.1': kubeadm=1.18.1-00

kubelet_versioned_pkg:
  '1.16.2': kubelet=1.16.2-00
  '1.18.1': kubelet=1.18.1-00

k8s_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ kubelet_versioned_pkg[k8s_version | string] }}"
    - name: "{{ kubeadm_versioned_pkg[k8s_version | string] }}"

kubelet_extra_config_file: /etc/default/kubelet
