---
# Should we move these to vars/common? They're used on:
#   task bringup_helm.yml
#   role restore-more-data.yml
source_helm_bind_dir: /opt/platform/helm_charts
target_helm_bind_dir: /var/www/pages/helm_charts
helm_repo_name_apps: starlingx
helm_repo_name_platform: stx-platform
# Protected directories that are not allowed in backup option 'exclude_dirs'
protected_backup_exclude_dirs:
  - /opt/dc-vault
  - /opt/dc-vault/*
  - /opt/dc-vault/**
  - /opt/dc-vault/**/*
  - /opt/dc-vault/ansible
  - /opt/dc-vault/ansible/*
  - /opt/dc-vault/ansible/**
  - /opt/dc-vault/ansible/**/*
