---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   These tasks are used to prestage patch packages and repodata.

- name: Copy patches Packages and repodata locally on {{ inventory_hostname }}
  command: rsync -ap --delete {{ host_patch_repo }}/ {{ patches_prestage_dir }}/
  when: prestage_source == 'local'

- block:
  # It's necessary to temporarily change the owner to sysadmin so that
  # the system controller can push the files to the subcloud, since the files
  # are in the folders only the root can access but the synchronize only
  # support passwordless sysadmin to execute ssh and rsync.
  - name: Temporarily change the ownership of the prestage patches dir on {{ inventory_hostname }}
    file:
      path: "{{ patches_prestage_dir }}"
      state: directory
      owner: sysadmin
      recurse: yes

  - name: Transfer patches Packages and repodata from the system controller
    synchronize:
      mode: push
      src: "{{ host_patch_repo }}/"
      dest: "{{ patches_prestage_dir }}/"
      rsync_opts: "--delete"
    register: patches_transfer
    retries: 3
    delay: 2
    until: patches_transfer.rc == 0

  - name: Restore the ownership of the prestage patches dir on {{ inventory_hostname }}
    file:
      path: "{{ patches_prestage_dir }}"
      state: directory
      owner: root
      recurse: yes
  when: prestage_source == 'remote'
