---
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Tasks to check LDAP user existence, to create LDAP users and set a new
# initial password, and to create the home directory. If the system is
# distributed cloud, it dynamically adds subclouds to the target host list.

- name: Check if LDAP user exists
  shell: ldapsearch -x -LLL uid={{ in_user_id }}
  register: in_user_id_check
  become: yes

- name: Create LDAP user only if it does not already exist
  block:
  - name: Set sudo_param if external variable sudo_permission is true
    set_fact:
      sudo_param: "{{ '--sudo' if in_sudo_permission else '' }}"

  - name: Set sys_protected_param if external variable sys_protected is true
    set_fact:
      sys_protected_param: "{{ '--secondgroup sys_protected' if in_sys_protected else '' }}"

  - name: Create LDAP user {{ in_user_id }}
    shell: >-
      ldapusersetup -u {{ in_user_id }} {{ sudo_param }} {{ sys_protected_param }} --passmax
      {{ password_change_period }} --passwarning {{ password_warning_period }}
    become: yes

  # In the following task, the string "LDAP Password" is found only in CentOS,
  # while the string "Current Password" is found only in Debian.
  - name: Change LDAP user initial password and create home directory
    expect:
      command: ssh {{ ssh_internal_args }} {{ in_user_id }}@localhost
      responses:
        s password: "{{ in_user_id }}"
        LDAP Password: "{{ in_user_id }}"
        Current Password: "{{ in_user_id }}"
        New password: "{{ in_user_password }}"
        new password: "{{ in_user_password }}"
        "\\~\\$": exit
    # do not show passwords in the logs
    no_log: true
  when: in_user_id_check.stdout == ""

- name: Get distributed cloud role
  include_role:
    name: manage-local-ldap-account/common/get-distributed-role

- name: Get online subclouds
  include_role:
    name: manage-local-ldap-account/common/get-online-subclouds

- name: Populate inventory with subclouds
  include_role:
    name: manage-local-ldap-account/common/add-hosts
  vars:
    in_item: "{{ item }}"
  loop: "{{ subcloud_list }}"
  when: is_dc | bool
