---
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Create LDAP user and set password.
#

- name: Create LDAP user
  block:
  - name: Set sudo_param if external variable sudo_permission is true
    set_fact:
      sudo_param: "{{ '--sudo' if in_sudo_permission else '' }}"

  - name: Set sys_protected_param if external variable sys_protected is true
    set_fact:
      sys_protected_param: "{{ '--secondgroup sys_protected' if in_sys_protected else '' }}"

  - name: Create LDAP user {{ in_user_id }}
    shell: >-
      ldapusersetup -u {{ in_user_id }} {{ sudo_param }} {{ sys_protected_param }} --passmax
      {{ in_password_change_period }} --passwarning {{ in_password_warning_period }}
    become: yes

  # In the following task, the string "LDAP Password" is found only in CentOS,
  # while the string "Current Password" is found only in Debian.
  - name: Change LDAP user initial password
    expect:
      command: ssh {{ ssh_internal_args }} {{ in_user_id }}@localhost
      responses:
        s password: "{{ in_user_id }}"
        LDAP Password: "{{ in_user_id }}"
        Current Password: "{{ in_user_id }}"
        New password: "{{ in_user_password }}"
        new password: "{{ in_user_password }}"
        "\\~\\$": exit
    # This task does not log sensitive information.
    # Setting this to no_log: false to allow better logging and debugging
    no_log: false
    register: change_password
    failed_when: false

  - name: Handle initial password change errors
    block:
      - name: Delete ldap user if initial password change was not successful
        shell: ldapdeleteuser {{ in_user_id }}
        become: yes

      - name: Fail if initial password change was not successful
        fail:
          msg: " {{ change_password.stdout }} \n\nFailed to change initial password, check the log above for more details."

    when: change_password.rc != 0
