---
#
# Copyright (c) 2023-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASK DESCRIPTION:
#   These tasks perform certificate expiry verification for Rest API
#   and Docker Registry certificates.
#
- name: Check if docker registry certificate file exists
  stat:
    path: /etc/ssl/private/registry-cert.crt
  register: registry_cert
  failed_when: not registry_cert.stat.exists
  become: yes

- name: Verify if Docker Registry certificate is expired
  command: openssl x509 -in /etc/ssl/private/registry-cert.crt -checkend 0
  register: registry_cert_expiration
  failed_when: false
  become: yes
  retries: 10
  delay: 6
  until: registry_cert_expiration.rc == 0

- name: Verify if HTTPS is enabled
  shell: |
    source /etc/platform/openrc; system show | awk '$2 == "https_enabled" { print $4 }'
  register: https_enabled

- block:
    - name: Check if Rest API certificate file exists
      stat:
        path: /etc/ssl/private/server-cert.pem
      register: restapi_cert
      failed_when: not restapi_cert.stat.exists

    - name: Verify if Rest API certificate is expired
      command: openssl x509 -in /etc/ssl/private/server-cert.pem -checkend 0
      register: restapi_cert_expiration
      failed_when: false
      retries: 10
      delay: 6
      until: restapi_cert_expiration.rc == 0

  become: yes
  when: https_enabled.stdout == "True"

- name: Fail if Rest API or Docker Registry certificates are expired
  fail:
    msg: >
      {% if restapi_cert_expiration.rc is defined and
            restapi_cert_expiration.rc != 0 and registry_cert_expiration.rc != 0 %}
      Rest API and Docker Registry certificates are expired.
      {% elif restapi_cert_expiration.rc is defined and restapi_cert_expiration.rc != 0 %}
      Rest API certificate is expired.
      {% elif registry_cert_expiration.rc != 0 %}
      Docker Registry certificate is expired.
      {% endif %}
      Manual action required! On the subcloud, please update the expired certificates with
      `system certificate-install` or, to use cert-manager, refer to the documentation in
      https://docs.starlingx.io/security/kubernetes/migrate-platform-certificates-to-use-cert-manager-c0b1727e4e5d.html.
      After completing this, run 'dcmanager subcloud delete' and
      'dcmanager subcloud add' again to restart the procedure.
  when: restapi_cert_expiration.rc is defined and
        restapi_cert_expiration.rc != 0 or
        registry_cert_expiration.rc != 0
