---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASK DESCRIPTION:
#   This task waits for the ssh password to sync between source and
#   target nodes by trying an ansible adhoc command a few times
#   until it succeeds.
#
- block:
  - name: Wait password to synchronize between nodes
    command: >-
      ansible all -i "{{ item }}," -m command -a "pwd"
      -e "ansible_ssh_user={{ ansible_ssh_user }} ansible_ssh_pass={{ ansible_ssh_pass }}"
    register: ssh_output
    failed_when: ssh_output.rc != 0
    no_log: true
    # May wait up to 15 mins, which is the interval at which AgentManager periodic task
    # will synchronize passwords
    retries: 5
    delay: 200
    until: ssh_output.rc == 0
  rescue:
    - name: Fail if password fail to sync to {{ item }} ( ssh fails )
      fail:
        msg: >-
          {{ item }} is not using the same password as controller-0.
          Please change it manually and try again.
