---
#
# Copyright (c) 2020,2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role is to configure a storage class for a Netapp backend
#

# Configure kubernetes storage class
- name: Set StorageClass filename
  set_fact:
    storageclass_file: "{{ trident_setup_dir }}/storage-class-{{ storage_class.metadata.name }}.yml"

- name: Set StorageClass headers
  set_fact:
    storageclass_headers:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass

- name: Prepare StorageClass content
  set_fact:
    storageclass: "{{ storageclass_headers | combine(storage_class) }}"

- name: Create storage-class.yaml
  copy:
    content: "{{ storageclass | to_nice_yaml }}"
    dest: "{{ storageclass_file }}"

- name: Remove StorageClass if it exists
  command: >
    "kubectl --kubeconfig=/etc/kubernetes/admin.conf
    -n {{ trident_namespace }}
    delete storageclass {{ storage_class.metadata.name }}"
  failed_when: false

- name: Create K8s StorageClass
  command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf -n {{ trident_namespace }} apply -f {{ storageclass_file }}"
