---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SUB-TASKS DESCRIPTION:
#   These tasks configure the credentials used in TridentBackendConfig
#

- name: Configure the credentials used in TridentBackendConfig
  block:
    - name: Set Trident backend config secret filename
      set_fact:
        secret_file: "{{ trident_setup_dir }}/backend_secret-{{ backend_secret.metadata.name }}.yml"

    - name: Set Trident backend config secret headers
      set_fact:
        secret_headers:
          apiVersion: v1
          kind: Secret

    - name: Prepare Trident backend config secret content
      set_fact:
        secret_yaml: "{{ secret_headers | combine(backend_secret) }}"

    - name: Create Trident backend config secret yaml file
      copy:
        content: "{{ secret_yaml | to_nice_yaml }}"
        dest: "{{ secret_file }}"

    - name: Remove Trident backend config secret if it exists
      command: >
        "kubectl -n {{ trident_namespace }}
        --kubeconfig=/etc/kubernetes/admin.conf
        delete secret {{ backend_secret.metadata.name }}"
      failed_when: false

    - name: Create Trident backend config secret
      command: "kubectl -n {{ trident_namespace }} --kubeconfig=/etc/kubernetes/admin.conf apply -f {{ secret_file }}"

  always:
    - name: Remove Trident backend config secret yaml file
      file:
        path: "{{ secret_file }}"
        state: absent
