---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role restores a subcloud from the specified backup file(s)
#   or software release.
#
- name: Validate user input
  import_tasks: validate_input.yml

- name: Prepare and transfer restore overrides to {{ inventory_hostname }}
  import_role:
    name: common/prepare-and-transfer-subcloud-overrides

- name: Perform platform restore
  import_tasks: do_platform_restore.yml

- name: Perform images restore
  import_tasks: do_images_restore.yml
  when: restore_registry_images and not optimized_bnr_supported

- name: Perform host unlock
  include_role:
    name: common/host-unlock
  vars:
    target_host: 'controller-0'

# On some hardware, the actual reboot after system host-unlock response is received may take
# longer than 60s. Wait up to 3 minutes for ssh port to become unavailable to ensure that the
# subcloud is actually rebooted by maintenance before executing the next task. The 3 minute
# timeout should be enough as mainteance will force reboot if it does not take place within
# 2 minutes.
- name: Wait up to {{ shutdown_timeout }} seconds for ssh port to become unavailable for {{ inventory_hostname }}
  local_action:
    module: wait_for
      port={{ ansible_port }}
      host={{ ansible_host }}
      delay=5
      timeout={{ shutdown_timeout }}
      state=stopped

- name: Wait up to {{ unlock_timeout }} seconds for ssh port to become available for {{ inventory_hostname }}
  local_action:
    module: wait_for
      port={{ ansible_port }}
      host={{ ansible_host }}
      delay=60
      timeout={{ unlock_timeout }}
      state=started

- name: Wait till all services are enabled-active
  shell: >-
    sm-dump | sed "1,/Services/d" | awk '{ print $3 }'
    | grep -v "enabled-active" | wc -l
  register: service_status_result
  until: service_status_result.stdout == "1"
  retries: 20
  delay: 30

- name: Run system restore-complete
  shell: source /etc/platform/openrc; system restore-complete
  register: restore_complete_result
  until: restore_complete_result.stdout == "Restore procedure completed"
  retries: 15
  delay: 10
