---
# Services related to docker
docker_services:
  - docker
  - "{{ 'docker-distribution' if os_release == 'centos' else 'docker-registry' }}"

# Used to remove containerd corruption after first boot
remove_containerd_pods_flag: /etc/platform/.remove_containerd_pods
