---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   Precheck to ensure the playbooks are executed on the system controller
#   and the overrides file is provided.
#
- name: Fail if playbook overrides parameter is not specified
  fail:
    msg: "Location of operation overrides must be specified."
  when: playbook_overrides is undefined

- name: Load input parameters for operation
  include_vars: "{{ playbook_overrides }}"

- name: Retrieve the distributed cloud role
  shell: source /etc/platform/platform.conf; echo $distributed_cloud_role
  register: dc_role
  connection: local

- name: Fail if the playbook is not run on the system controller
  fail:
    msg: >
      This playbook is intended to be executed on the system controller
      of a distributed cloud system.
  when: dc_role.stdout != 'systemcontroller'
