---
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Tasks to populate the inventory with managed subclouds.

- name: Populate inventory with subclouds
  add_host:
    name: "{{ in_item }}"
    groups: "subclouds"
    in_user_id: "{{ in_user_id }}"
    ssh_internal_args: "{{ ssh_internal_args }}"
    in_sudo_permission: "{{ in_sudo_permission }}"
    in_sys_protected: "{{ in_sys_protected }}"
    in_mode: "{{ in_mode }}"
    in_user_password: "{{ in_user_password if in_mode == 'create' else '' }}"
    in_user_role: "{{ in_user_role if in_mode == 'create' else '' }}"
