---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   Setup networking so that restoring can be completed.
#   Networking should match the state it would be in after
#   completing a typical bootstrapping, so that unlocking can
#   be performed immediately after optimized restore is complete.

- name: Remove network configuration files
  file:
    path: "{{ network_scripts_location }}"
    state: absent

- name: Restore network configuration files
  command: "tar -C / -xpf {{ platform_backup_fqpn }} --overwrite {{ network_scripts_location.lstrip('/') }}"

- name: Bring up original networking
  shell:
    cmd: |
      ifup $(ls ifcfg-* | sed 's/ifcfg-//') --ignore-errors --force
    chdir: /etc/network/interfaces.d/
  async: 60
  poll: 5

- name: Bring up temporary addresses
  block:
    - name: Lookup controller host addresses
      shell: "grep -E '{{ '|'.join(temporary_address_names) }}' /etc/hosts | awk '{print $1}'"
      register: host_addresses

    - name: Check if host address is up
      shell: "ping {{ item }} -c1 -w5 | grep ' 0% packet loss'"
      failed_when: false
      loop: "{{ host_addresses.stdout_lines }}"
      register: checked_addresses

    - name: Configure missing controller host address
      command: "ip addr add {{ item.item }} dev lo scope host"
      when: item.rc != 0
      loop: "{{ checked_addresses.results }}"
