---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   Setup networking so that restoring can be completed.
#   Networking should match the state it would be in after
#   completing a typical bootstrapping, so that unlocking can
#   be performed immediately after optimized restore is complete.

# Bring up networking, meant to replicate state during boostrapping
- name: Restore networking
  block:
    - name: Determine network configuration files
      find:
        paths: "{{ network_scripts_location }}"
        patterns: "ifcfg-*"
      register: network_files_to_delete

    - name: Remove network configuration files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ network_files_to_delete.files }}"

    - name: Restore network configuration files
      command: "tar -C / -xpf {{ platform_backup_fqpn }} --overwrite --wildcards {{ network_scripts_location_bkp }}/*"

    # fails due to enp0s9 not having the ip set on ifcfg-enp0s9
    # - name: Restart networking daemon
    #   systemd:
    #     name: networking
    #     state: restarted

    - name: Bring lo up
      command: ifup lo lo:1 lo:5

    - name: Lookup controller host address
      command: "gethostip -d controller"
      register: host_lookup

    - name: Define controller host address
      set_fact:
        controller_address: "{{ host_lookup.stdout_lines[0] }}"

    - name: Configure controller host address
      command: "ip addr add {{ controller_address }} dev lo scope host"

    - name: Lookup controller host address
      command: "gethostip -d pxecontroller"
      register: pxe_host_lookup

    - name: Define controller host address
      set_fact:
        pxecontroller_address: "{{ pxe_host_lookup.stdout_lines[0] }}"

    - name: Configure controller host address
      command: "ip addr add {{ pxecontroller_address }} dev lo scope host"

  ignore_errors: true
