---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   Setup networking so that restoring can be completed.
#   Networking should match the state it would be in after
#   completing a typical bootstrapping, so that unlocking can
#   be performed immediately after optimized restore is complete.

# Bring up networking, meant to replicate state during bootstrapping
- name: Restore networking
  block:
    - name: Remove network configuration files
      file:
        path: "{{ network_scripts_location }}"
        state: absent

    - name: Restore network configuration files
      command: "tar -C / -xpf {{ platform_backup_fqpn }} --overwrite {{ network_scripts_location.lstrip('/') }}"

    - name: Get IPv4 default gateways
      shell: >
        ip -4 route show default
        | grep -oE 'dev [0-9a-z]+'
        | awk '{print "--exclude=" $2}'
      register: ipv4_route

    # There can be multiple default routes
    - name: Get IPv6 default gateways
      shell: >
        ip -6 route show default
        | grep -oE 'dev [0-9a-z]+'
        | awk '{print "--exclude=" $2}'
      register: ipv6_route

    - name: Extract gateway interfaces
      set_fact:
        interfaces: "{{
            ipv4_route.stdout_lines + ipv6_route.stdout_lines
            | map('trim') | reject('equalto', '')
            | unique | list
          }}"

    # Ignore errors is used here to avoid any issues
    # with networking interfaces that could not be produced
    # during regular usage and testing.
    # Interfaces will be brought up normally after unlocking.
    - name: Bring up original networking
      shell:
        cmd: |
          ifdown -a --exclude=lo {{ ' '.join(interfaces) }}
          ifup $(ls ifcfg-* | sed 's/ifcfg-//') --ignore-errors
        chdir: /etc/network/interfaces.d/

    - name: Bring up temporary addresses
      block:
      - name: Lookup controller host addresses
        shell: "grep -E '{{ '|'.join(temporary_address_names) }}' /etc/hosts | awk '{print $1}'"
        register: host_addresses

      - name: Configure controller host address
        command: "ip addr add {{ item }} dev lo scope host"
        loop: "{{ host_addresses.stdout_lines }}"
