---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASK DESCRIPTION:
#   The tasks below restore luks volume content

- name: Set parameters used by luks tasks
  set_fact:
    archive_luks_fs_path: "{{ luks_fs_path | regex_replace('^\\/', '') }}"

- name: Check if luks volume configuration is present in the backup tarball
  shell: "tar --use-compress-program=pigz -tf {{ restore_data_file }} | grep 'created_luks.json'"
  args:
    warn: false
  failed_when: false
  register: bkp_has_luks_config

- name: Ensure luks-fs-mgr service is running
  systemd:
    name: "luks-fs-mgr"
    state: started
  when: bkp_has_luks_config.rc is defined and
        bkp_has_luks_config.rc == 0

- name: Pause for service initialization
  pause:
    seconds: 30
  when: bkp_has_luks_config.rc is defined and
        bkp_has_luks_config.rc == 0

- name: Restore luks filesystem content
  command: >-
    tar -C {{ luks_fs_path }} -xpf {{ platform_backup_fqpn }}  --strip-components=4
    {{ archive_luks_fs_path }}
  args:
    warn: false
  when: bkp_has_luks_config.rc is defined and
        bkp_has_luks_config.rc == 0
