---
#
# Copyright (c) 2021-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Simple util to delete kubernetes resources by name and namespace
#
- name: Delete kubernetes resources
  command: >-
    kubectl delete {{ item.type }}
    --ignore-not-found=true
    {{ item.name }}
    -n {{ item.namespace }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: command_output
  until: command_output is not failed
  retries: 10
  delay: 30
