---
#
# Copyright (c) 2020 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role loads variables containing images.
#

- set_fact:
    kubernetes_version: "{{ lookup('file', 'roles/common/files/kubeadm.yaml.erb') |
      regex_search('^kubernetesVersion: (.*)$', multiline=True) | regex_replace('^(.*): (.*)$', '\\2')}}"
  when: mode == 'bootstrap' or
        mode == 'restore' or
        mode == 'trident_install' or
        mode == 'backup'

- block:
  - name: Get the list of kubernetes images
    shell: "kubeadm --kubeconfig=/etc/kubernetes/admin.conf config images list --kubernetes-version {{ kubernetes_version }}"
    register: kubernetes_images_output

  - set_fact:
      kubernetes_images: "{{ kubernetes_images_output.stdout_lines }}"

  - name: Read in system images list
    include_vars:
      dir: "vars/k8s-{{ kubernetes_version }}"
      files_matching: "system-images.yml"

# Optional system images can be addded in {{ additional_system_images_conf_file }}
# under {{ additional_system_images_conf_path }}.
# Additional static images can be introduced in this file, e.g.
# additional_static_images_list:
#   image1_name: <registry-url>/image1:v1.0
#   image2_name: <registry-url>/image2:v2.0
# Additional static images required or a DC controller only can also be introduced in this file, e.g.
# additional_system_controller_static_images_list:
#   image3_name: <registry-url>/image3:v3.0
#   image4_name: <registry-url>/image4:v4.0
  - name: Check if additional image config directory exists
    stat:
      path: "{{ additional_system_images_conf_path }}"
    register: additional_config_dir

  - name: Read in additional system images list(s)
    include_vars:
      dir: "{{ additional_system_images_conf_path }}"
      files_matching: "{{ additional_system_images_conf_file }}"
    when: additional_config_dir.stat.exists and additional_config_dir.stat.isdir

  - name: Categorize system images
    set_fact:
      networking_images:
        - "{{ calico_cni_img }}"
        - "{{ calico_node_img }}"
        - "{{ calico_kube_controllers_img }}"
        - "{{ calico_flexvol_img }}"
        - "{{ multus_img }}"
        - "{{ sriov_cni_img }}"
        - "{{ sriov_network_device_img }}"
      static_images:
        - "{{ tiller_img }}"
        - "{{ armada_img }}"
        - "{{ n3000_opae_img }}"
        - "{{ kubernetes_entrypoint_img }}"
      storage_images:
        - "{{ snapshot_controller_img }}"

  - name: Append additional static images if provisioned
    set_fact:
      static_images: "{{ static_images }} + [ '{{item.value}}' ]"
    with_items: "{{ additional_static_images_list | default({})| dict2items }}"
    when: additional_static_images_list is defined

  - block:
    - name: Append RVMC image for a DC system controller
      set_fact:
        static_images: "{{ static_images }} + [ '{{ rvmc_img }}' ]"

    - name: Append additional static images for a DC system controller if provisioned
      set_fact:
        static_images: "{{ static_images }} + [ '{{item.value}}' ]"
      with_items: "{{ additional_system_controller_static_images_list | default({})| dict2items }}"
      when: additional_system_controller_static_images_list is defined

    when: (distributed_cloud_role is defined and
           distributed_cloud_role == 'systemcontroller') or
          (check_dc_controller is defined and
           check_dc_controller.rc == 0)

  when: kubernetes_version is defined
