---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is to clear the old network configuration from the subcloud
#   in the post network reconfiguration
#

- name: Delete the admin address pool if the target network is mgmt
  shell: >-
    source /etc/platform/openrc; system addrpool-delete
    {{ admin_addrpool }}
  when: admin_addrpool and target_net == mgmt_net

- name: Delete old routes on controller-0
  shell: >-
    source /etc/platform/openrc; system host-route-delete
    {{ item }}
  with_items: "{{ existing_routes_c0.stdout_lines }}"
  when: existing_routes_c0.stdout_lines | length > 0

- block:
  - name: Delete old routes on controller-1
    shell: >-
      source /etc/platform/openrc; system host-route-delete
      {{ item }}
    with_items: "{{ existing_routes_c1.stdout_lines }}"
    when: existing_routes_c1.stdout_lines | length > 0
  when: system_mode != "simplex"
