---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is to clear the old network configuration from the subcloud
#   in the post network reconfiguration
#

- block:
  - name: Check admin address pool uuid
    shell: >-
      source /etc/platform/openrc; system addrpool-list |
      awk '$4 == "admin" { print $2 }'
    register: admin_addrpool_uuid

  - name: Delete admin address pool if is configured
    shell: >-
      source /etc/platform/openrc; system addrpool-delete
      {{ admin_addrpool_uuid.stdout }}
    when: admin_addrpool_uuid.stdout != ""

  - name: Check admin host route
    shell: >-
      source /etc/platform/openrc; system host-route-list controller-0 |
      awk '$4 == "admin0" { print $2 }'
    register: admin_route_uuid

  - name: Delete admin host route if is configured
    shell: >-
      source /etc/platform/openrc; system host-route-delete
      {{ admin_route_uuid.stdout }}
    when: admin_route_uuid.stdout != ""

  # TODO(nicodemos) This should be removed after sysinv/puppet handle removing
  # the admin-ip service if admin network and interface doesn't exist
  - name: Unmanage admin-ip service
    command: sm-unmanage service admin-ip
    become: yes
  when: target_net == 'mgmt'

- block:
  - name: Check mgmt host route
    shell: >-
      source /etc/platform/openrc; system host-route-list controller-0 |
      awk '$4 == "mgmt0" { print $2 }'
    register: mgmt_route_uuid

  - name: Delete mgmt host route if is configured
    shell: >-
      source /etc/platform/openrc; system host-route-delete
      {{ mgmt_route_uuid.stdout }}
    when: mgmt_route_uuid.stdout != ""
  when: target_net == 'admin'
