---
#
# Copyright (c) 2021 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role checks related services are all enabled-active before
#   finishing the rehome playbook
#

- name: Check all services are enabled-active
  shell: >-
    sm-dump | sed "1,/Services/d" | awk "{ print $2 }"
    | grep -v "enabled-active" | wc -l
  register: service_status_result
  until: service_status_result.stdout == "1"
  retries: 5
  delay: 30
  become: yes
