---
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# The file has tasks to get/set some flags related to subclouds from
# central system controller. This role also builds the list of subclouds
# that are currently online and managed to be used in the next play.

- name: Set os_param_region_name if system is a DC
  set_fact:
    os_param_region_name: "{{ '--os-region-name SystemController' if is_dc | bool else '' }}"

- name: Tasks for distributed cloud
  block:
  - name: Get subcloud list
    shell: |
      source /etc/platform/openrc
      dcmanager subcloud list --format yaml
    register: subcloud_list_result

  - name: Set a list for subclouds
    set_fact:
      subcloud_list: "{{ subcloud_list | default([]) + [ item.name ] }}"
    when: (item.management == "managed" and item.availability == "online")
    loop: "{{ subcloud_list_result.stdout | from_yaml if subcloud_list_result.stdout else [] }}"

  when: is_dc | bool
