---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASK DESCRIPTION:
#   The tasks below restore the postgres database schema and data.

- set_fact:
    postgres_staging_dir: "{{ staging_dir }}/postgres"

- block:
  - name: Create staging directory for postgres data
    file:
      path: "{{ postgres_staging_dir }}"
      state: directory
      recurse: yes
      owner: root
      group: root
      mode: 0755

  - name: Extract postgres db to staging directory
    command: >-
      tar -C {{ staging_dir }}/postgres -xpf {{ platform_backup_fqpn }}
      --wildcards --transform='s,.*/,,' '*/*\.postgreSql\.*'
    args:
      warn: false

  - name: Copy database table to csv
    block:
    - name: Remove temporary db.csv file if present
      file:
        path: "/tmp/db.csv"
        state: absent

    - name: Save ssl_ca certificates from postgres database to /tmp/db.csv
      command: >-
        psql -d sysinv -c "copy (select * from
        certificate where certtype='ssl_ca') to
        '/tmp/db.csv' with delimiter ';'"
    become_user: postgres
    when: ssl_ca_certificate_file is defined and ssl_ca_certificate_file is not none

  - name: Determine which postgresql database files exist
    stat:
      path: "{{ postgres_staging_dir }}/{{ item }}"
    with_items:
      - "postgres.postgreSql.config"
      - "postgres.postgreSql.data"
      - "template1.postgreSql.data"
      - "sysinv.postgreSql.data"
      - "keystone.postgreSql.data"
      - "fm.postgreSql.data"
      - "barbican.postgreSql.data"
    register: pgfiles

  - name: Restore postgres db
    shell: "psql -f {{ item.stat.path }} {{ item.item.split('.')[0] }}"
    become_user: postgres
    with_items: "{{ pgfiles.results }}"
    when: item.stat.exists

  - name: Update ssl_ca certificates in sysinv database
    block:
    - name: Reset system table id sequence
      command: >-
        psql -d sysinv -c
        "ALTER SEQUENCE certificate_id_seq
        RESTART WITH 1000;
        UPDATE certificate SET id=nextval('certificate_id_seq');"

    - name: Remove ssl_ca certificates from system database
      command: psql -d sysinv -c "delete from certificate where certtype='ssl_ca'"

    - name: Replace ssl_ca certificates by the ones saved in /tmp/db.csv
      command: >-
        psql -d sysinv -c
        "copy certificate from
        '/tmp/db.csv' with delimiter ';'
        WHERE expiry_date > NOW();"

    - name: Re-sync system table row count after insert ssl_ca certificates
      command: >-
        psql -d sysinv -c
        "SELECT setval('certificate_id_seq',
        (SELECT MAX(id) FROM certificate)+1);
        UPDATE certificate SET id=nextval('certificate_id_seq');"

    - name: Restore system table row count
      command: >-
        psql -d sysinv -c
        "ALTER SEQUENCE certificate_id_seq
        RESTART WITH 1;
        UPDATE certificate SET id=nextval('certificate_id_seq');"

    - name: Remove temporary db.csv
      file:
        path: "/tmp/db.csv"
        state: absent
    become_user: postgres
    when: ssl_ca_certificate_file is defined and ssl_ca_certificate_file is not none

  - import_tasks: restore-postgres-dc.yml

  - import_tasks: aio-sx-node-replacement.yml

  - name: Remove postgres staging directory
    file:
      path: "{{ postgres_staging_dir }}"
      state: absent

  - name: Restart postgres
    systemd:
      name: postgresql
      state: restarted

  when: migrate_platform_data is undefined or not migrate_platform_data
