---
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASK DESCRIPTION:
#   The tasks below restore the postgres Distributed Cloud related data.

- name: Check if the system is a DC controller
  command: >-
    grep -i "distributed_cloud_role\s*=\s*systemcontroller"
    /etc/platform/platform.conf
  register: check_dc_controller
  failed_when: false

- name: Restore postgres for DC
  block:

  - name: Determine which postgresql database files exist
    stat:
      path: "{{ postgres_staging_dir }}/{{ item }}"
    with_items:
      - "dcmanager.postgreSql.data"
      - "dcorch.postgreSql.data"
    register: pgfiles_dc

  - name: Restore postgres db for DC systemcontroller
    shell: "psql -f {{ item.stat.path }} {{ item.item.split('.')[0] }}"
    become_user: postgres
    with_items: "{{ pgfiles_dc.results }}"
    when: item.stat.exists

  - name: Extract .subcloud_alarm.csv if exist
    command: >-
      tar -C /tmp -xpf {{ platform_backup_fqpn }}
      --wildcards '*/*\.subcloud_alarm.csv' --strip-components=4
    failed_when: false

  - name: Check if .subcloud_alarm.csv exists
    stat:
      path: "/tmp/.subcloud_alarm.csv"
    register: subcloud_alarm_csv_file

  - name: Restore subcloud alarms
    block:
      - name: Move alarms from .subcloud_alarm.csv to alarm table
        command: >-
          psql -d fm -c
          "copy alarm from
          '/tmp/.subcloud_alarm.csv' with delimiter ';'"
        become_user: postgres

      - name: Remove temporary .subcloud_alarm.csv file.
        file:
          path: "/tmp/.subcloud_alarm.csv"
          state: absent
        become: yes

    when: subcloud_alarm_csv_file.stat.exists

  when: check_dc_controller.rc == 0
