---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#   This role is to check the target host environment before proceeding to
#   the next step.
#

- name: Get subcloud active controller
  shell: |
    source /etc/platform/openrc
    system host-show $(cat /etc/hostname) --column hostname --format value
  register: controller_name

- name: Set subcloud floating address fact
  set_fact:
    sc_floating_address: "{{ sc_floating_address }}"

- name: Retrieve software version number
  # lookup module does not work with /etc/build.info as it does not have ini
  # format. Resort to shell source.
  shell: source /etc/build.info; echo $SW_VERSION
  register: sw_version_result

- name: Fail if software version is not defined
  fail:
    msg: "SW_VERSION is missing in /etc/build.info"
  when: sw_version_result.stdout_lines|length == 0

- name: Retrieve system mode
  shell: source /etc/platform/platform.conf; echo $system_mode
  register: system_mode_result

- name: Fail if system mode is not defined
  fail:
    msg: "system_mode is missing in /etc/platform/platform.conf"
  when: system_mode_result.stdout_lines|length == 0

- name: Set host software version, system mode
  set_fact:
    software_version: "{{ sw_version_result.stdout }}"
    system_mode: "{{ system_mode_result.stdout }}"

- name: Set config path fact
  set_fact:
    config_permdir: "{{ platform_path + '/config/' + software_version }}"

- name: Get target subcloud network
  shell: >-
    source /etc/platform/openrc; system addrpool-list |
    grep "{{ sc_floating_address }}" | awk '{print $4}'
  register: target_net_raw

- name: Set the target network name variable
  set_fact:
    target_net: "{{ 'mgmt' if target_net_raw.stdout == 'management' else target_net_raw.stdout }}"

- name: Get ifname of the existing subcloud network of controller-0
  shell: >-
    source /etc/platform/openrc; system interface-network-list controller-0 |
    awk '$8 == "{{ target_net }}" { print $6 }'
  register: controller_0_sc_network_if

- name: Fail if subcloud network interface of controller-0 is not assigned
  fail:
    msg: "No interface is assigned to {{ target_net }} on controller-0"
  when: controller_0_sc_network_if.stdout == ""

- name: Set sc_if_c0 fact
  set_fact:
    sc_if_c0: "{{ controller_0_sc_network_if.stdout_lines[0] }}"

- block:
  - name: Get ifname of the existing subcloud network of controller-1
    shell: >-
      source /etc/platform/openrc; system interface-network-list controller-1 |
      awk '$8 == {{ target_net }} { print $6 }'
    register: controller_1_sc_network_if

  - name: Set sc_if_c1 fact
    set_fact:
      sc_if_c1: "{{ controller_1_sc_network_if.stdout_lines[0] }}"

  - name: Fail if subcloud network interface of controller-1 is not assigned
    fail:
      msg: "No interface is assigned to {{ target_net }} on controller-1"
    when: controller_1_sc_network_if.stdout == ""

  when: system_mode != "simplex"
