---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   These tasks update the subcloud's admin network configurations.
#

- name: Get previous subcloud admin network address pool uuid
  shell: >-
    source /etc/platform/openrc; system network-list |
    awk '$8 == "admin" { print $12 }'
  register: subcloud_admin_pool_uuid

- name: Delete previous subcloud admin network address pool
  shell: >-
    source /etc/platform/openrc; system addrpool-delete
    {{ subcloud_admin_pool_uuid.stdout }}
  when: subcloud_admin_pool_uuid.stdout | length > 0

- name: Add subcloud admin network address pool
  shell: >-
    source /etc/platform/openrc; system addrpool-add admin
    {{ (admin_subnet | ipaddr(0)).split('/')[0]  }}
    {{ admin_subnet | ipaddr('prefix') }}
    --ranges {{ admin_floating_address }}-{{ admin_floating_address | ipmath(2) }}
    --gateway-address {{ admin_gateway_address }}  |
    awk '/uuid/{ print$4 }'
  register: add_subcloud_admin_pool_uuid

- name: Add new subcloud admin network
  shell: >-
    source /etc/platform/openrc;
    system network-add admin admin false
    {{ add_subcloud_admin_pool_uuid.stdout }}

- name: Add new subcloud admin interface network association on controller-0
  shell: >-
    source /etc/platform/openrc;
    system interface-network-assign controller-0
    {{ admin_if_c0 }} admin

- name: Add new subcloud admin interface network association on controller-1
  shell: >-
    source /etc/platform/openrc;
    system interface-network-assign controller-1
    {{ admin_if_c1 }} admin
  when: system_mode != 'simplex'

- name: Query config-out-of-date alarm
  shell: |
    source /etc/platform/openrc;
    fm alarm-list --query alarm_id=250.001
  register: alarm_count
  retries: 5
  delay: 10
  until: alarm_count.stdout != ""

- name: Check manifest applied and alarm cleared
  shell: |
    source /etc/platform/openrc;
    fm alarm-list --query alarm_id=250.001
  register: alarm_count
  retries: 10
  delay: 30
  until: alarm_count.stdout == ""
  # set as false to allow for a better error message in the fail task below
  failed_when: false

- name: Failed when the manifest apply times out
  fail:
    msg: >-
      Timed out while updating admin subnet. Check the puppet.log on the
      subcloud controller for the reason.
  when: alarm_count.stdout != ""
