---
#
# Copyright (c) 2021-2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role updates the openstack keystone data(Ids, passwords)
#   in database, reloads the configurations of related services and
#   restarts these services
#

- name: Backup keystone config
  command: "cp /etc/keystone/keystone.conf /tmp/keystone.conf"

- name: Temporarily disable lockout in keystone
  lineinfile:
    path: "/etc/keystone/keystone.conf"
    regexp: "^{{ item }}"
    state: absent
  loop:
    - "lockout_failure_attempts"
    - "lockout_duration"

- name: Restart keystone service post config update
  import_tasks: restart_keystone.yml

- name: Migrate keystone passwords
  import_tasks: migrate_keystone_passwords.yml

- name: Migrate keystone IDs
  import_tasks: migrate_keystone_ids.yml

- name: Restore keystone original config
  command: "mv /tmp/keystone.conf /etc/keystone/keystone.conf"

- name: Restart keystone service post config update
  import_tasks: restart_keystone.yml

- name: Restart vim service
  command: "sm-restart service vim"

- name: Check vim enabled after restart
  shell: sm-query service vim | grep -c enabled-active
  register: service_status
  until: service_status.stdout == '1'
  retries: 12
  delay: 10
