---
#
# Copyright (c) 2021-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role updates the openstack keystone data(Ids, passwords)
#   in database, reloads the configurations of related services and
#   restarts these services
#

- name: Gather facts of keystone.conf
  stat:
    path: "{{ keystone_conf }}"
  register: keystone_conf_facts

- name: Backup keystone config
  copy:
    src: "{{ keystone_conf }}"
    dest: "/tmp/keystone.conf"
    mode: preserve
    remote_src: yes

- name: Temporarily disable lockout in keystone
  lineinfile:
    path: "{{ keystone_conf }}"
    regexp: "^{{ item }}"
    state: absent
  loop:
    - "lockout_failure_attempts"
    - "lockout_duration"

- name: Restart keystone service post config update
  import_tasks: restart_keystone.yml

- name: Migrate keystone passwords
  import_tasks: migrate_keystone_passwords.yml

- name: Migrate keystone IDs
  import_tasks: migrate_keystone_ids.yml

- name: Restore keystone original config
  copy:
    src: "/tmp/keystone.conf"
    dest: "{{ keystone_conf }}"
    owner: "{{ keystone_conf_facts.stat.uid }}"
    group: "{{ keystone_conf_facts.stat.gid }}"
    mode: preserve
    remote_src: yes

- name: Remove backup keystone config
  file:
    path: "/tmp/keystone.conf"
    state: absent

- name: Restart keystone service post config update
  import_tasks: restart_keystone.yml

- name: Restart vim service
  command: "sm-restart service vim"

- name: Check vim enabled after restart
  shell: sm-query service vim | grep -c enabled-active
  register: service_status
  until: service_status.stdout == '1'
  retries: 12
  delay: 10
