---
#
# Copyright (c) 2021-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   These tasks update docker registry credentials, keystone passwords in keystone
#   database, secure hieradata, relevant service config files as well as service
#   passwords in keyring.
#

- name: Prepare user list
  set_fact:
    user_list:
      - { username: 'barbican', password: "{{ users['barbican'] }}", service: 'barbican-keystone-listener' }
      # dcmanager related services are not running on the subcloud.
      - { username: 'dcmanager', password: "{{ users['dcmanager'] }}", service: 'dcmanager' }
      - { username: 'fm', password: "{{ users['fm'] }}", service: 'fm-mgr' }
      - { username: 'mtce', password: "{{ users['mtce'] }}", service: 'mtc-agent' }
      - { username: 'patching', password: "{{ users['patching'] }}", service: 'sw-patch-controller-daemon' }
      - { username: 'vim', password: "{{ users['vim'] }}", service: 'vim' }

# The hieradata must be changed before the keystone_listener is notified to apply
# the password change runtime puppet, because the puppet will use the new passwords
# in the hieradata to replace those in each service configuration file and restart
# the corresponding service.
- name: Update services' passwords in hieradata secure_static.yaml
  lineinfile:
    path: "/opt/platform/puppet/{{ software_version }}/hieradata/secure_static.yaml"
    regexp: "{{ item.From }}"
    line: "{{ item.To }}"
  loop:
    - { From: "^barbican::keystone::auth::password",
        To: "barbican::keystone::auth::password: !!python/unicode '{{ users['barbican'] }}'" }
    - { From: "^barbican::keystone::authtoken::password",
        To: "barbican::keystone::authtoken::password: !!python/unicode '{{ users['barbican'] }}'" }
    - { From: "^dcmanager::api::keystone_password",
        To: "dcmanager::api::keystone_password: !!python/unicode '{{ users['dcmanager'] }}'" }
    - { From: "^dcmanager::keystone::auth::password",
        To: "dcmanager::keystone::auth::password: !!python/unicode '{{ users['dcmanager'] }}'" }
    - { From: "^dcorch::api_proxy::dcmanager_keystone_password",
        To: "dcorch::api_proxy::dcmanager_keystone_password: !!python/unicode '{{ users['dcmanager'] }}'" }
    - { From: "^fm::auth::auth_password",
        To: "fm::auth::auth_password: !!python/unicode '{{ users['fm'] }}'" }
    - { From: "^fm::keystone::auth::password",
        To: "fm::keystone::auth::password: !!python/unicode '{{ users['fm'] }}'" }
    - { From: "^fm::keystone::authtoken::password",
        To: "fm::keystone::authtoken::password: !!python/unicode '{{ users['fm'] }}'" }
    - { From: "^nfv::keystone::auth::password",
        To: "nfv::keystone::auth::password: !!python/unicode '{{ users['vim'] }}'" }
    - { From: "^patching::api::keystone_password",
        To: "patching::api::keystone_password: !!python/unicode '{{ users['patching'] }}'" }
    - { From: "^patching::keystone::auth::password",
        To: "patching::keystone::auth::password: !!python/unicode '{{ users['patching'] }}'" }
    - { From: "^patching::keystone::authtoken::password",
        To: "patching::keystone::authtoken::password: !!python/unicode '{{ users['patching'] }}'" }
    - { From: "^platform::mtce::params::auth_pw",
        To: "platform::mtce::params::auth_pw: !!python/unicode '{{ users['mtce'] }}'" }
    - { From: "^sysinv::api::keystone_password",
        To: "sysinv::api::keystone_password: !!python/unicode '{{ users['sysinv'] }}'" }
    - { From: "^sysinv::certalarm::dc_keystone_password",
        To: "sysinv::certalarm::dc_keystone_password: !!python/unicode '{{ users['dcmanager'] }}'" }
    - { From: "^sysinv::certalarm::local_keystone_password",
        To: "sysinv::certalarm::local_keystone_password: !!python/unicode '{{ users['sysinv'] }}'" }
    - { From: "^sysinv::certmon::dc_keystone_password",
        To: "sysinv::certmon::dc_keystone_password: !!python/unicode '{{ users['dcmanager'] }}'" }
    - { From: "^sysinv::certmon::local_keystone_password",
        To: "sysinv::certmon::local_keystone_password: !!python/unicode '{{ users['sysinv'] }}'" }
    - { From: "^sysinv::keystone::auth::password",
        To: "sysinv::keystone::auth::password: !!python/unicode '{{ users['sysinv'] }}'" }
  no_log: true

- name: Update registry password in hieradata secure_system.yaml
  lineinfile:
    path: "/opt/platform/puppet/{{ software_version }}/hieradata/secure_system.yaml"
    regexp: "^platform::dockerdistribution::params::registry_password"
    line: "platform::dockerdistribution::params::registry_password: !!python/unicode '{{ users['sysinv'] }}'"
  no_log: true

- name: Update keystone user passwords
  include_tasks: update_keystone_user_password.yml
  vars:
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    service: "{{ item.service }}"
  loop: "{{ user_list }}"
  no_log: true

- name: Store sysinv service password in keyring
  vars:
    script_content: |
      import keyring
      import os
      os.environ['XDG_DATA_HOME'] = "/opt/platform/.keyring/{{ software_version }}"
      keyring.set_password("sysinv", "services", "{{ users['sysinv'] }}")
  shell: "{{ script_content }}"
  args:
    executable: /usr/bin/python
  no_log: true

# There's a race condition that the sysinv conductor running with the old sysinv
# password may not able to get the openstack users list after updating the new
# sysinv password in keystone. Manually update the password and reload the services
# on controller-0 to ensure the sysinv servies are running with new password.
- name: Update sysinv password in configuration on the active controller
  lineinfile:
    path: "{{ item }}"
    regexp: "^password=.*$"
    line: "password={{ users['sysinv'] }}"
  loop:
    - "/etc/sysinv/sysinv.conf"
    - "/etc/sysinv/api-paste.ini"
    - "/etc/sysinv/cert-mon.conf"
    - "/etc/sysinv/cert-alarm.conf"
  no_log: true

- name: Update sysinv password in keystone
  shell: >-
    source /etc/platform/openrc;
    openstack user set 'sysinv' --password $'{{ users['sysinv'] }}';

- name: Restart sysinv services to update the config in controller-0
  command: sm-restart-safe service "{{ item }}"
  loop:
    - "sysinv-inv"
    - "sysinv-conductor"
    - "cert-alarm"
    - "cert-mon"

- name: Check sysinv-conductor related services enabled
  shell: sm-query service '{{ item }}' | grep -c enabled-active
  loop:
    - "sysinv-inv"
    - "cert-mon"
    - "cert-alarm"
    - "sysinv-conductor"
  register: service_status
  until: service_status.stdout == '1'
  retries: 12
  delay: 10

- block:
  # the sysinv password is expected to be updated on controller-0 at this moment,
  # leveraging the healthy sysinv-conductor to update the config in controller-1
  - name: Store the sysinv old config uuid of controller-0
    shell: source /etc/platform/openrc; system host-show controller-0
            | grep -i "config_applied"
    register: c0_old_config_uuid

  - name: Store the sysinv old config uuid of controller-1
    shell: source /etc/platform/openrc; system host-show controller-1
            | grep -i "config_applied"
    register: c1_old_config_uuid

  - name: Updating sysinv password to trigger manifest updating controller-1
    shell: >-
      source /etc/platform/openrc;
      openstack user set 'sysinv' --password $'{{ users['sysinv'] }}';

  - name: Wait for sysinv agent to apply sysinv::password::runtime on controller-0
    shell: source /etc/platform/openrc; system host-show controller-0
            | grep -i "config_applied"
    register: c0_new_config_uuid
    until: c0_old_config_uuid.stdout != c0_new_config_uuid.stdout
    retries: 30
    delay: 10

  - name: Wait for sysinv agent to apply sysinv::password::runtime on controller-1
    shell: source /etc/platform/openrc; system host-show controller-1
            | grep -i "config_applied"
    register: c1_new_config_uuid
    until: c1_old_config_uuid.stdout != c1_new_config_uuid.stdout
    retries: 18
    delay: 10
  when: system_mode != "simplex"

- name: Update docker registry credentials
  command: "update_docker_registry_auth.sh 'sysinv' '{{ users['sysinv'] }}'"
  no_log: true
