---
#
# Copyright (c) 2021-2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   These tasks are to migrate the keystone IDs in keystone DB and hieradata.
#

- name: Migrate keystone user IDs
  script: migrate_keystone_ids.py {{ item.name }} {{ item.id }} 'user'
  with_items:
    - { name: 'admin', id: "{{ system_controller_keystone_admin_user_id }}" }
    - { name: 'sysinv', id: "{{ system_controller_keystone_sysinv_user_id }}" }
    - { name: 'dcmanager', id: "{{ system_controller_keystone_dcmanager_user_id }}" }
  become_user: postgres
  no_log: true

- name: Migrate keystone project IDs
  script: migrate_keystone_ids.py {{ item.name }} {{ item.id }} 'project'
  with_items:
    - { name: 'admin', id: "{{ system_controller_keystone_admin_project_id }}" }
    - { name: 'services', id: "{{ system_controller_keystone_services_project_id }}" }
  become_user: postgres
  no_log: true

- name: Flush memcached
  shell: echo flush_all > /dev/tcp/{{ derived_network_params.controller_0_address }}/11211

- name: Restart keystone service
  import_tasks: restart_keystone.yml

- name: Restart affected services using sm
  command: "sm-restart service {{ item }}"
  loop:
    - "vim-api"
    - "barbican-api"
    - "sysinv-conductor"

- name: Restart affected services using pmon
  command: "pmon-restart {{ item }}"
  loop:
    - "fm-api"
    - "sm-api"

- name: Wait until services are restarted after changing keystone IDs
  shell: sm-query service {{ item }} | grep -c enabled-active
  loop:
    - "vim-api"
    - "barbican-api"
    - "sysinv-conductor"
    - "sysinv-inv"
    - "cert-mon"
    - "cert-alarm"
  register: service_status
  until: service_status.stdout == '1'
  retries: 10
  delay: 10
