---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASK DESCRIPTION:
#   The tasks below update the config db configuration in slapd.conf and schema files
#   TODO (rjosemat): remove when Centos -> Debian upgrade support become deprecated
#

- name: Get _LDAPADMIN_PW_ from slapd.conf
  shell: grep "rootpw {SSHA}" /etc/ldap/slapd.conf.backup | head -n1 | awk '{ print $2 }'
  register: ldap_admin_root_pw

- name: Ensure slapd.conf has a db entry for config
  blockinfile:
    path: /etc/ldap/slapd.conf.backup
    marker: "# {mark} CONFIG BLOCK ADDED WITH ANSIBLE"
    insertbefore: "database        mdb"
    block: |
      # olcDatabase={0}config
      database        config
      rootdn          "cn=config"
      rootpw          {{ ldap_admin_root_pw.stdout }}

- name: Remove old configuration
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/ldap/schema/cn=config
    - /etc/ldap/schema/cn=config.ldif

- name: Apply new configuration
  shell: /usr/sbin/slaptest -f /etc/ldap/slapd.conf.backup -F /etc/ldap/schema/
