---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is add static route to the system controller via the
#   subcloud subnet
#

- name: Check existing host route in controller-0
  shell: >-
    source /etc/platform/openrc; system host-route-list controller-0 |
    awk '/{{ sc_gateway_address }}/'
  register: existing_route_controller_0

- name: Add static route from controller-0 to system controller
  shell: >-
    source /etc/platform/openrc; system host-route-add controller-0
    {{ sc_if_c0 }}
    {{ system_controller_network }}
    {{ system_controller_network_prefix }}
    {{ sc_gateway_address }}
  when: existing_route_controller_0.stdout | length == 0

- block:
  - name: Check existing host route in controller-1
    shell: >-
      source /etc/platform/openrc; system host-route-list controller-1 |
      awk '/{{ sc_gateway_address }}/'
    register: existing_route_controller_1

  - name: Add static route from controller-1 to system controller
    shell: >-
      source /etc/platform/openrc; system host-route-add controller-1
      {{ sc_if_c1 }}
      {{ system_controller_network }}
      {{ system_controller_network_prefix }}
      {{ sc_gateway_address }}
    when: existing_route_controller_1.stdout | length == 0
  when: system_mode != 'simplex'
